name: Scheduled Fork Sync

on:
  schedule:
    # 每天凌晨 0点（UTC时间）自动执行，等同于北京时间上午 8点
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发同步

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-Action@v3.4.1
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          # 上游仓库（用户名/仓库名）
          upstream_sync_repo: "freestylefly/WeChatBridge"
          # 上游分支
          upstream_sync_branch: "main"
          # 本地 Fork 仓库的目标分支
          target_sync_branch: "main"
          # 设为 false 表示正式同步
          test_mode: false
